name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.4
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  rxdart: ^0.28.0
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
